import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {createServer} from 'node:http';import {HocuspocusProvider} from '@hocuspocus/provider';import * as Y from 'yjs';
import {testPostgres} from '../scripts/test-postgres.ts';import {migrate} from '../packages/database/migrate.ts';import {Database,one} from '../packages/database/index.ts';import {buildApp} from '../apps/api/src/app.ts';import {createCollab} from '../apps/collab/src/server.ts';import {tick} from '../apps/worker/src/worker.ts';import {createSession,csrf} from '../packages/auth/index.ts';import {signature} from '../packages/events/index.ts';
let pg:any,db:Database,app:any,collab:any,dir:string,owner:any,member:any,guest:any,other:any,root:any,space:any,page:any,database:any,record:any,file:any,service:any;
const providers:HocuspocusProvider[]=[];
const req=async(method:string,path:string,data?:any,actor=owner,extra:any={})=>{const headers:any={...(actor?{cookie:actor.cookie,'x-csrf-token':actor.csrf}:{}),...extra};if(data!==undefined&&!headers['content-type'])headers['content-type']='application/json';return app.inject({method,url:`/api/v1${path}`,headers,...(data!==undefined?{payload:data}: {})});};
const ok=async(method:string,path:string,data?:any,actor=owner)=>{const r=await req(method,path,data,actor);assert.ok(r.statusCode<300,`${method} ${path}: ${r.statusCode} ${r.body}`);return r.json();};
function session(r:any){const cookie=r.headers['set-cookie'].split(';')[0];return{cookie,csrf:csrf(cookie.split('=')[1])};}
const pause=(n:number)=>new Promise(r=>setTimeout(r,n));
async function until(fn:()=>boolean|Promise<boolean>){for(let i=0;i<80;i++){if(await fn())return;await pause(100);}throw Error('Timed out waiting for condition');}
async function invite(role:string){const v=await ok('POST','/members/invite',{name:role,email:`${role}@example.test`,role});const r=await req('POST','/auth/accept-invite',{token:new URL(v.url).searchParams.get('invite'),password:'test-password-123'},null);assert.equal(r.statusCode,200,r.body);const a=session(r);return{...a,...(await ok('GET','/me',undefined,a)).user};}
async function connect(a=owner,p=page){const ticket=await ok('POST',`/pages/${p.id}/collab`,{},a),doc=new Y.Doc();const provider=new HocuspocusProvider({url:'ws://127.0.0.1:1235',name:ticket.name,token:ticket.token,document:doc});providers.push(provider);await until(()=>provider.synced);return{provider,doc};}
before(async()=>{process.env.ENCRYPTION_KEY='a'.repeat(64);process.env.SETUP_TOKEN='test-setup-token';process.env.COOKIE_SECURE='false';dir=await mkdtemp(`${tmpdir()}/workspace-test-`);process.env.STORAGE_LOCAL_PATH=dir;pg=await testPostgres(55433);await migrate(pg.url);db=new Database(pg.url,{serialize:pg.emulated});app=await buildApp(db,undefined,false);const r=await req('POST','/setup',{organisation:'Acme',workspace:'HQ',name:'Owner',email:'owner@example.test',password:'test-password-123',demo:false},null,{'x-setup-token':process.env.SETUP_TOKEN});assert.equal(r.statusCode,200,r.body);owner=session(r);const me=await ok('GET','/me');owner={...owner,...me.user,tenant:me.organisation.id};root=(await ok('GET','/resources'))[0];space=await ok('POST','/resources',{kind:'space',parent_id:root.id,title:'Engineering'});page=await ok('POST','/resources',{kind:'page',parent_id:space.id,title:'A confidential design'});member=await invite('member');guest=await invite('guest');const tenant=(await ok('POST','/organisations',{name:'Other tenant'})).id;const t=await db.tenant(tenant,q=>createSession(q,tenant,owner.id));other={cookie:`workspace_session=${t}`,csrf:csrf(t),tenant};collab=await createCollab(db,1235);});
after(async()=>{providers.forEach(p=>p.destroy());await collab?.close();await app?.close();await db?.close();await pg?.close();await rm(dir,{recursive:true,force:true});});
test('setup is one-time and writes require CSRF',async()=>{assert.equal((await req('POST','/setup',{organisation:'X',workspace:'X',name:'X',email:'x@test.co',password:'long-password-1'},null,{'x-setup-token':'test-setup-token'})).statusCode,409);assert.equal((await req('PATCH',`/resources/${page.id}`,{title:'No'},owner,{'x-csrf-token':''})).statusCode,403);});
test('native row-level policies and known IDs isolate tenants',async()=>{assert.equal((await req('GET',`/resources/${page.id}`,undefined,other)).statusCode,404);assert.equal((await db.tenant(other.tenant,q=>q.query('SELECT * FROM resources WHERE id=$1',[page.id]))).rowCount,0);assert.equal((await req('GET',`/resources/${page.id}`,undefined,guest)).statusCode,404);assert.equal((await req('POST',`/pages/${page.id}/collab`,{},other)).statusCode,404);});
test('tree moves reject cycles and invalid parent types',async()=>{const child=await ok('POST','/resources',{kind:'page',parent_id:page.id,title:'Nested'});assert.equal((await req('PATCH',`/resources/${page.id}`,{parent_id:child.id})).statusCode,400);assert.equal((await req('PATCH',`/resources/${space.id}`,{parent_id:page.id})).statusCode,400);});
test('canonical replacement, body search, versions and restore',async()=>{await ok('PATCH',`/pages/${page.id}/content`,{blocks:[{type:'paragraph',content:'Unique body evidence Orion'}],expected_revision:1});assert((await ok('GET','/search?q=Orion')).some((x:any)=>x.id===page.id));assert.equal((await req('PATCH',`/pages/${page.id}/content`,{blocks:[],expected_revision:1})).statusCode,409);const versions=await ok('GET',`/pages/${page.id}/versions`);await ok('POST',`/pages/${page.id}/versions/${versions[0].id}/restore`,{expected_revision:2});assert.equal((await ok('GET',`/pages/${page.id}/content`)).epoch,3);});
test('typed records, optimistic concurrency, saved filters and full bodies',async()=>{database=await ok('POST','/resources',{kind:'database',parent_id:space.id,title:'Delivery',template:'tasks'});record=await ok('POST',`/databases/${database.id}/records`,{values:{name:'Ship product',status:'Not started',priority:'High',assignee:member.id}});record=await ok('PATCH',`/records/${record.id}`,{values:{status:'In progress'},expected_revision:1});assert.equal((await req('PATCH',`/records/${record.id}`,{values:{status:'Done'},expected_revision:1})).statusCode,409);assert.equal((await req('PATCH',`/records/${record.id}`,{values:{due:'bad'},expected_revision:2})).statusCode,400);const v=await ok('POST',`/databases/${database.id}/views`,{name:'Active',config:{type:'board',groupBy:'status',filters:[{property:'status',op:'eq',value:'In progress'}]}});assert.equal((await ok('GET',`/databases/${database.id}/records?view=${v.id}`)).length,1);assert.equal((await ok('GET',`/pages/${record.id}/content`)).revision,1);assert.equal((await req('GET',`/records/${record.id}`,undefined,other)).statusCode,404);});
test('two Yjs clients converge, persist canonical text, and reconnect',async()=>{const a=await connect(),b=await connect(member);a.doc.getMap('test').set('one','first');b.doc.getMap('test').set('two','second');const fragment=a.doc.getXmlFragment('document');function find(v:any):any{if(v instanceof Y.XmlText)return v;for(const child of v.toArray?.()||[]){const f=find(child);if(f)return f;}}let text=find(fragment);if(!text){function paragraph(v:any):any{if(v.nodeName==='paragraph')return v;for(const child of v.toArray?.()||[]){const found=paragraph(child);if(found)return found;}}const p=paragraph(fragment);assert(p);text=new Y.XmlText();p.insert(0,[text]);}text.insert(0,'Live collaboration evidence');await until(()=>a.doc.getMap('test').get('two')==='second'&&b.doc.getMap('test').get('one')==='first');await until(async()=>(await ok('GET',`/pages/${page.id}/content`)).plain_text.includes('Live collaboration evidence'));a.provider.destroy();b.provider.destroy();const c=await connect();assert.equal(c.doc.getMap('test').get('two'),'second');c.provider.destroy();});
test('comments create mentions and block unauthorized moderation',async()=>{const c=await ok('POST',`/resources/${page.id}/comments`,{body:`Please review @{${member.id}}`});assert.equal((await ok('GET','/notifications',undefined,member)).length,1);assert.equal((await req('PATCH',`/resources/${page.id}/comments/${c.id}`,{body:'changed'},member)).statusCode,403);await ok('PATCH',`/resources/${page.id}/comments/${c.id}`,{resolved:true},member);});
test('private uploads validate type and authorize parent on every download',async()=>{const boundary='test-boundary';const data=`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="evidence.txt"\r\nContent-Type: text/plain\r\n\r\nPrivate evidence\r\n--${boundary}--\r\n`;const r=await req('POST',`/resources/${page.id}/files`,data,owner,{'content-type':`multipart/form-data; boundary=${boundary}`});assert.equal(r.statusCode,200,r.body);file=r.json();assert.equal((await req('GET',`/files/${file.id}/content`)).body,'Private evidence');assert.equal((await req('GET',`/files/${file.id}/content`,undefined,other)).statusCode,404);assert.equal((await req('GET',`/files/${file.id}/content`,undefined,guest)).statusCode,404);});
test('ancestor permission revocation removes API, search, file and live access',async()=>{const c=await connect(member);let reset=false;c.provider.on('stateless',({payload}:any)=>{if(JSON.parse(payload).type==='reset')reset=true;});await ok('PATCH',`/resources/${space.id}/permissions`,{inherit:false,grants:[]});await until(()=>reset);assert.equal((await req('GET',`/pages/${page.id}/content`,undefined,member)).statusCode,404);assert.equal((await req('GET',`/files/${file.id}/content`,undefined,member)).statusCode,404);assert.equal((await ok('GET','/search?q=Live',undefined,member)).length,0);assert.equal((await req('GET',`/records/${record.id}`,undefined,member)).statusCode,404);c.provider.destroy();await ok('PATCH',`/resources/${space.id}/permissions`,{inherit:true,grants:[]});});
test('service principals default to no access and read scopes cannot write',async()=>{service=await ok('POST','/integrations',{name:'Intelligence'});const s={cookie:'',csrf:''};const bearer={authorization:`Bearer ${service.token}`};assert.equal((await req('GET',`/pages/${page.id}/content`,undefined,s,bearer)).statusCode,404);await ok('PATCH',`/resources/${root.id}/permissions`,{inherit:true,grants:[{principal_id:service.principal_id,level:1}]});assert.equal((await req('GET',`/pages/${page.id}/content`,undefined,s,bearer)).statusCode,200);assert.equal((await req('PATCH',`/pages/${page.id}/content`,{blocks:[],expected_revision:1},s,bearer)).statusCode,403);assert.equal((await req('GET',`/pages/${page.id}/content`,undefined,{cookie:`workspace_session=${service.token}`,csrf:''})).statusCode,401);});
test('outbox dispatch signs webhooks and records retries',async()=>{let received:any;const receiver=createServer((r,res)=>{let body='';r.on('data',b=>body+=b);r.on('end',()=>{received={body,headers:r.headers};res.end('ok');});});await new Promise<void>(r=>receiver.listen(49661,'127.0.0.1',r));process.env.WEBHOOK_ALLOWED_ORIGINS='http://127.0.0.1:49661,http://127.0.0.1:49662';try{assert.equal((await req('POST','/webhooks',{url:'http://169.254.169.254/latest',events:['page.updated']})).statusCode,400);const h=await ok('POST','/webhooks',{url:'http://127.0.0.1:49661/events',events:['page.updated']});await ok('POST','/webhooks',{url:'http://127.0.0.1:49662/events',events:['page.updated']});await ok('PATCH',`/resources/${page.id}`,{title:'Live design'});await tick(db);assert(received);assert.equal(received.headers['x-workspace-signature'],`sha256=${signature(h.secret,received.headers['x-workspace-timestamp'],received.body)}`);assert((await ok('GET','/webhooks')).deliveries.some((d:any)=>d.status==='retry'));}finally{receiver.close();}});
test('imports run asynchronously and recheck current permissions',async()=>{const j=await ok('POST','/imports',{parent_id:space.id,name:'Imported knowledge',format:'markdown',content:'# Imported\n\nDurable details'},member);await tick(db);const job=await ok('GET',`/jobs/${j.id}`,undefined,member);assert.equal(job.status,'completed');assert((await ok('GET',`/pages/${job.result.resource_id}/content`)).plain_text.includes('Durable details'));const csv=await ok('POST','/imports',{parent_id:space.id,name:'Imported CSV',format:'csv',content:'Name,Owner\nFirst,Jane\nSecond,John'});await tick(db);assert.equal((await ok('GET',`/jobs/${csv.id}`)).status,'completed');const denied=await ok('POST','/imports',{parent_id:space.id,name:'Must fail',format:'markdown',content:'private'},member);await ok('PATCH',`/resources/${space.id}/permissions`,{inherit:false,grants:[]});await tick(db);const status=await db.tenant(owner.tenant,q=>one(q,'SELECT status FROM jobs WHERE id=$1',[denied.id]));assert.equal(status.status,'failed');await ok('PATCH',`/resources/${space.id}/permissions`,{inherit:true,grants:[]});});
test('exports have canonical text and formula-safe CSV',async()=>{assert((await req('GET',`/resources/${page.id}/export?format=markdown`)).body.includes('Live collaboration'));await ok('POST',`/databases/${database.id}/records`,{values:{name:'=HYPERLINK("evil")'}});assert((await req('GET',`/resources/${database.id}/export?format=csv`)).body.includes("'=HYPERLINK"));});
test('trash cascade is atomic and restore preserves content',async()=>{await ok('DELETE',`/resources/${space.id}`);assert.equal((await req('GET',`/pages/${page.id}/content`)).statusCode,404);assert.equal((await req('POST',`/resources/${page.id}/restore`,{})).statusCode,404);await ok('POST',`/resources/${space.id}/restore`,{});await ok('POST',`/resources/${page.id}/restore`,{});assert((await ok('GET',`/pages/${page.id}/content`)).plain_text.includes('Live collaboration'));});
test('audit is append-only to runtime role and credentials revoke immediately',async()=>{await assert.rejects(db.tenant(owner.tenant,q=>q.query('DELETE FROM audit_events')));await ok('PATCH',`/members/${member.id}`,{active:false});assert.equal((await req('GET','/me',undefined,member)).statusCode,401);assert((await ok('GET','/audit')).length>0);});
