export const featureExamples = {
  home: "Use your workspace as the front door for team knowledge, active projects, meeting notes and operating dashboards.",
  recent: "Use Recently viewed to jump back into the pages and databases you were working in without hunting through the tree.",
  favourites: "Favourite the pages, dashboards and reference material you need every day so they stay one click away.",
  templates: "Start recurring work from a template — for example, use the same project brief or meeting-note structure every time.",
  trash: "Restore a page that was deleted by mistake, or review old material before it is permanently removed.",
  search: "Search for a project name, customer, policy phrase or task and open only results you already have permission to see.",
  create: "Create a page for a project brief, a space for a department, or a database for structured work such as tasks or assets.",
  import: "Bring an existing CSV task list or Markdown knowledge page into Workspace instead of rebuilding it manually.",
  inbox: "Use Inbox to catch mentions, replies and page updates that need your attention.",
  notificationPreferences: "Turn mention or reply alerts on or off depending on how you want Workspace to interrupt you.",
  page: "Use a page for a project brief, SOP, meeting note or research document, then link it to related work.",
  space: "Use a space to group a department, programme or client area and keep its pages and databases together.",
  record: "Use a record as one structured item — for example, a task, customer, asset, risk or action — with its own page content.",
  backlinks: "Link a project page from meeting notes and Workspace will show those notes here as backlinks automatically.",
  comments: "Discuss a specific page or block, mention a teammate and resolve the thread when the decision is made.",
  permissions: "Keep a finance or HR page private while letting the wider team access the parent space.",
  history: "Review an earlier revision after a large edit and restore it without deleting the newer history.",
  files: "Attach supporting evidence such as a signed PDF, screenshot or source document directly to the page.",
  activity: "Use activity to see who changed, commented on or updated a page when you need an audit trail.",
  database: "Use a database to manage structured work such as projects, tasks, suppliers, assets or risks in one place.",
  databaseViews: "Create different views of the same records — for example, a table for operations, a board by status and a calendar by due date.",
  databaseProperties: "Add fields such as owner, status, due date, relation or formula so records reflect how your team actually works.",
  members: "Invite teammates and assign the smallest role they need; for example, give a contractor guest access instead of full membership.",
  profile: "Manage your own sign-in and display preferences without affecting how teammates see their workspace.",
  branding: "Apply your organisation name, logo and identity so the workspace feels like an internal company product.",
  integrations: "Create a service credential when an approved internal system needs scoped API access to Workspace.",
  sso: "Register your company identity provider so staff can eventually sign in with the same corporate account they use elsewhere.",
  scim: "Connect directory provisioning so joining or leaving the company can automatically add or revoke Workspace access.",
  webhooks: "Send Workspace events to another system — for example, notify an operations service when a record or page changes.",
  audit: "Review the audit trail when investigating who changed access, configuration or other sensitive workspace settings.",
} as const;

export type FeatureExampleKey = keyof typeof featureExamples;
